name = "vpn"
main = "_worker.js"
compatibility_date = "2024-05-20"

[vars]
ROOT_DOMAIN = "lucka.biz.id"
SERVICE_NAME = "vpn"

[env.production]
vars = { 
  API_KEY = "CVPGmCXJ4fimaJ-Y6-XjLtkZC3C5_tNOir1DOxfZ",
  API_EMAIL = "dhills.citizenk@gmail.com",
  ACCOUNT_ID = "bfa559c07654f675a3e7744376f36b47",
  ZONE_ID = "f7cab408c61a317dbad39a31b64f8dce"
}

[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true
