name = "nautica"
main = "_worker.js"
compatibility_date = "2024-05-20"

[vars]
ROOT_DOMAIN = "foolvpn.me"
SERVICE_NAME = "nautica"

[env.production]
vars = { 
  API_KEY = "@cf_api_key",
  API_EMAIL = "@cf_email",
  ACCOUNT_ID = "@cf_account_id",
  ZONE_ID = "@cf_zone_id"
}
